// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libexperimentation_client";



        [DllImport(__DllName, EntryPoint = "expt_last_error_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int expt_last_error_length();

        [DllImport(__DllName, EntryPoint = "expt_last_error_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* expt_last_error_message();

        [DllImport(__DllName, EntryPoint = "expt_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void expt_free_string(byte* s);

        [DllImport(__DllName, EntryPoint = "expt_new_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int expt_new_client(byte* tenant, CULong update_frequency, byte* hostname);

        [DllImport(__DllName, EntryPoint = "expt_start_polling_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void expt_start_polling_update(byte* tenant);

        [DllImport(__DllName, EntryPoint = "expt_free_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void expt_free_client(Arc* ptr);

        [DllImport(__DllName, EntryPoint = "expt_get_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Arc* expt_get_client(byte* tenant);

        [DllImport(__DllName, EntryPoint = "expt_get_applicable_variant", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* expt_get_applicable_variant(Arc* client, byte* c_context, short toss);

        [DllImport(__DllName, EntryPoint = "expt_get_satisfied_experiments", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* expt_get_satisfied_experiments(Arc* client, byte* c_context, byte* filter_prefix);

        [DllImport(__DllName, EntryPoint = "expt_get_filtered_satisfied_experiments", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* expt_get_filtered_satisfied_experiments(Arc* client, byte* c_context, byte* filter_prefix);

        [DllImport(__DllName, EntryPoint = "expt_get_running_experiments", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* expt_get_running_experiments(Arc* client);


    }



}
