// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace LibCacClient
{
    internal static unsafe partial class Client
    {
        const string __DllName = "libcac_client";



        [DllImport(__DllName, EntryPoint = "cac_last_error_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int cac_last_error_length();

        [DllImport(__DllName, EntryPoint = "cac_last_error_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* cac_last_error_message();

        [DllImport(__DllName, EntryPoint = "cac_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cac_free_string(byte* s);

        [DllImport(__DllName, EntryPoint = "cac_new_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int cac_new_client(byte* tenant, CULong update_frequency, byte* hostname);

        [DllImport(__DllName, EntryPoint = "cac_start_polling_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cac_start_polling_update(byte* tenant);

        [DllImport(__DllName, EntryPoint = "cac_free_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cac_free_client(Arc* ptr);

        [DllImport(__DllName, EntryPoint = "cac_get_client", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Arc* cac_get_client(byte* tenant);

        [DllImport(__DllName, EntryPoint = "cac_get_last_modified", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* cac_get_last_modified(Arc* client);

        [DllImport(__DllName, EntryPoint = "cac_get_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* cac_get_config(Arc* client, byte* filter_query, byte* filter_prefix);

        [DllImport(__DllName, EntryPoint = "cac_get_resolved_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* cac_get_resolved_config(Arc* client, byte* query, byte* filter_keys, byte* merge_strategy);

        [DllImport(__DllName, EntryPoint = "cac_get_default_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* cac_get_default_config(Arc* client, byte* filter_keys);


    }



}
